import {
  AlertTriangle,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  Command,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  Loader2,
  Moon,
  Github,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  SunMedium,
  Trash,
  Twitter,
  User,
  X,
  Home,
  Search,
  MessageSquare,
  LogOut,
  Menu,
  Upload,
  Send,
  Lightbulb,
  BookOpen,
  Instagram,
  Linkedin,
  Star,
  Calendar,
  Clock,
  MapPin,
  DollarSign,
  Briefcase,
  Award,
  Zap,
  Heart,
  Share2,
  Bookmark,
  ExternalLink,
  CheckCircle,
  AlertCircle,
  Info,
  Paperclip,
  Link,
  Edit,
  Save,
  Download,
  BarChart,
  PieChart,
  LineChart,
  Users,
  Building,
  GraduationCap,
  Code,
  Layers,
  Cpu,
  Database,
  Server,
  Globe,
  Monitor,
  Smartphone,
  Tablet,
  Headphones,
  Camera,
  Video,
  Music,
  Film,
  Play,
  Pause,
  SkipBack,
  SkipForward,
  Shuffle,
  Repeat,
  Volume2,
  VolumeX,
  Mic,
  MicOff,
  Phone,
  Mail,
  Lock,
  Unlock,
  Key,
  FileKey,
  Shield,
  ShieldCheck,
  ShieldAlert,
  Eye,
  EyeOff,
  Filter,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ChevronUp,
  ChevronDown,
  RefreshCw,
  RotateCw,
  RotateCcw,
  Maximize,
  Minimize,
  Copy,
  Clipboard,
  List,
  CheckSquare,
  Square,
  Circle,
  CircleCheck,
  ToggleLeft,
  ToggleRight,
  Gauge,
  Bell,
  BellRing,
  BellOff,
  Wallet,
  ShoppingCart,
  Gift,
  Tag,
  Receipt,
  PenTool,
  Stethoscope,
  Utensils,
  Sofa,
  Bed,
  Sunrise,
  Sunset,
  Umbrella,
  Gamepad,
  Puzzle,
  Palette,
  Brush,
  Pen,
  Pencil,
  Eraser,
  Scissors,
  Printer,
  Facebook,
  Layout,
  Folder,
  Package,
  Box,
  Activity,
  Pill,
  Dna,
  ThumbsUp,
  type LucideIcon,
} from "lucide-react"

export type Icon = LucideIcon

export const Icons = {
  logo: Command,
  logOut : LogOut,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  check: Check,
  x: X,
  home: Home,
  search: Search,
  messageSquare: MessageSquare,
  logout: LogOut,
  menu: Menu,
  upload: Upload,
  send: Send,
  github: Github,
  lightbulb: Lightbulb,
  bookOpen: BookOpen,
  twitter: Twitter,
  instagram: Instagram,
  linkedin: Linkedin,
  facebook: Facebook,
  star: Star,
  compass: ArrowRight,
  calendar: Calendar,
  clock: Clock,
  mapPin: MapPin,
  dollarSign: DollarSign,
  briefcase: Briefcase,
  award: Award,
  zap: Zap,
  heart: Heart,
  share: Share2,
  bookmark: Bookmark,
  externalLink: ExternalLink,
  checkCircle: CheckCircle,
  alertCircle: AlertCircle,
  info: Info,
  paperclip: Paperclip,
  link: Link,
  edit: Edit,
  save: Save,
  download: Download,
  barChart: BarChart,
  pieChart: PieChart,
  lineChart: LineChart,
  users: Users,
  building: Building,
  graduationCap: GraduationCap,
  code: Code,
  layers: Layers,
  cpu: Cpu,
  database: Database,
  server: Server,
  globe: Globe,
  monitor: Monitor,
  smartphone: Smartphone,
  tablet: Tablet,
  headphones: Headphones,
  camera: Camera,
  video: Video,
  music: Music,
  film: Film,
  play: Play,
  pause: Pause,
  skipBack: SkipBack,
  skipForward: SkipForward,
  shuffle: Shuffle,
  repeat: Repeat,
  volume: Volume2,
  mute: VolumeX,
  mic: Mic,
  micOff: MicOff,
  phone: Phone,
  mail: Mail,
  lock: Lock,
  unlock: Unlock,
  key: Key,
  fileKey: FileKey,
  shield: Shield,
  shieldCheck: ShieldCheck,
  shieldAlert: ShieldAlert,
  eye: Eye,
  eyeOff: EyeOff,
  filter: Filter,
  sort: ArrowUp,
  sortAsc: ArrowUp,
  sortDesc: ArrowDown,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  arrowLeft: ArrowLeft,
  chevronUp: ChevronUp,
  chevronDown: ChevronDown,
  plus: Plus,
  minus: X,
  refresh: RefreshCw,
  rotate: RotateCw,
  rotateCcw: RotateCcw,
  maximize: Maximize,
  minimize: Minimize,
  copy: Copy,
  clipboard: Clipboard,
  list: List,
  circle: Circle,
  circleCheck: CircleCheck,
  square: Square,
  checkSquare: CheckSquare,
  toggle: ToggleLeft,
  toggleRight: ToggleRight,
  sliders: Filter,
  gauge: Gauge,
  bell: Bell,
  bellRing: BellRing,
  bellOff: BellOff,
  wallet: Wallet,
  creditCard: CreditCard,
  shoppingCart: ShoppingCart,
  gift: Gift,
  tag: Tag,
  receipt: Receipt,
  fileText: FileText,
  folderOpen: Folder,
  folder: Folder,
  package: Package,
  box: Box,
  cog: Settings,
  wrench: Settings,
  tool: PenTool,
  activity: Activity,
  heartPulse: Heart,
  stethoscope: Stethoscope,
  pill: Pill,
  dna: Dna,
  pizza: Pizza,
  utensils: Utensils,
  lightbulb: Lightbulb,
  bed: Bed,
  sofa: Sofa,
  sunrise: Sunrise,
  dollar: DollarSign,
  sunset: Sunset,
  umbrella: Umbrella,
  gamepad: Gamepad,
  puzzle: Puzzle,
  palette: Palette,
  brush: Brush,
  pen: Pen,
  pencil: Pencil,
  eraser: Eraser,
  scissors: Scissors,
  paperclip: Paperclip,
  printer: Printer,
  message: MessageSquare,
  thumbsUp: ThumbsUp,
  layout: Layout,
  image: Image,
  camera: Camera,
  school: GraduationCap,
  alertTriangle: AlertTriangle,
  video: Video,
  music: Music, 
  thumbsUp: ThumbsUp,
}

