// Recruiter users data
export const recruiterUsers = [
  {
    id: "recruiter-1",
    fullName: "Jessica Reynolds",
    email: "jessica.reynolds@techtalent.com",
    phone: "+1 (555) 789-0123",
    company: "TechTalent Solutions",
    position: "Senior Technical Recruiter",
    profileImage: "/placeholder.svg?height=200&width=200",
    bio: "Experienced technical recruiter specializing in software engineering and product roles for tech startups and established companies.",
    industries: ["Software Development", "AI/ML", "FinTech"],
    activeRoles: [
      {
        id: "role-1",
        title: "Senior Frontend Developer",
        company: "TechCorp",
        skills: ["React", "TypeScript", "Next.js", "GraphQL"],
      },
      {
        id: "role-2",
        title: "Machine Learning Engineer",
        company: "AI Innovations",
        skills: ["Python", "TensorFlow", "Machine Learning", "Data Science"],
      },
      {
        id: "role-3",
        title: "Full Stack Developer",
        company: "FinTech Solutions",
        skills: ["React", "Node.js", "MongoDB", "Express"],
      },
    ],
  },
  {
    id: "recruiter-2",
    fullName: "Michael Chen",
    email: "michael.chen@innovatehire.com",
    phone: "+1 (555) 234-5678",
    company: "InnovateHire",
    position: "Tech Talent Acquisition Manager",
    profileImage: "/placeholder.svg?height=200&width=200",
    bio: "Talent acquisition professional focused on connecting innovative startups with top engineering talent.",
    industries: ["Startups", "E-commerce", "Health Tech"],
    activeRoles: [
      {
        id: "role-4",
        title: "UI/UX Designer",
        company: "DesignHub",
        skills: ["UI/UX Design", "Figma", "Adobe XD", "User Research"],
      },
      {
        id: "role-5",
        title: "Backend Developer",
        company: "HealthTech Inc",
        skills: ["Python", "Django", "PostgreSQL", "API Development"],
      },
    ],
  },
  {
    id: "recruiter-3",
    fullName: "Samantha Williams",
    email: "samantha.williams@talentbridge.com",
    phone: "+1 (555) 345-6789",
    company: "TalentBridge",
    position: "University Relations Recruiter",
    profileImage: "/placeholder.svg?height=200&width=200",
    bio: "Specialized in campus recruiting and early career talent acquisition for technology roles.",
    industries: ["Education Tech", "Consumer Tech", "Social Impact"],
    activeRoles: [
      {
        id: "role-6",
        title: "Junior Software Engineer",
        company: "EduTech",
        skills: ["JavaScript", "React", "Node.js", "Entry Level"],
      },
      {
        id: "role-7",
        title: "Data Analyst Intern",
        company: "DataInsights",
        skills: ["SQL", "Python", "Data Visualization", "Excel"],
      },
      {
        id: "role-8",
        title: "Product Manager Associate",
        company: "SocialGood",
        skills: ["Product Management", "Agile", "User Research"],
      },
    ],
  },
  {
    id: "recruiter-4",
    fullName: "David Rodriguez",
    email: "david.rodriguez@techrecruit.com",
    phone: "+1 (555) 456-7890",
    company: "TechRecruit Global",
    position: "Technical Recruiting Director",
    profileImage: "/placeholder.svg?height=200&width=200",
    bio: "Experienced recruiting director with a background in engineering. Specialized in building diverse technical teams.",
    industries: ["Enterprise Software", "Cybersecurity", "Cloud Computing"],
    activeRoles: [
      {
        id: "role-9",
        title: "DevOps Engineer",
        company: "CloudSecure",
        skills: ["AWS", "Kubernetes", "Docker", "CI/CD", "Terraform"],
      },
      {
        id: "role-10",
        title: "Security Engineer",
        company: "CyberDefense",
        skills: ["Cybersecurity", "Network Security", "Penetration Testing"],
      },
    ],
  },
  {
    id: "recruiter-5",
    fullName: "Olivia Thompson",
    email: "olivia.thompson@creativetalent.com",
    phone: "+1 (555) 567-8901",
    company: "Creative Talent Solutions",
    position: "Design & Creative Recruiter",
    profileImage: "/placeholder.svg?height=200&width=200",
    bio: "Specialized in recruiting for design, UX, and creative technology roles across industries.",
    industries: ["Design Agencies", "Product Companies", "Media & Entertainment"],
    activeRoles: [
      {
        id: "role-11",
        title: "Senior UX Designer",
        company: "UserFirst",
        skills: ["UX Design", "User Research", "Prototyping", "Design Systems"],
      },
      {
        id: "role-12",
        title: "Creative Technologist",
        company: "MediaTech",
        skills: ["JavaScript", "WebGL", "Three.js", "Creative Coding"],
      },
      {
        id: "role-13",
        title: "Product Designer",
        company: "DesignForward",
        skills: ["Product Design", "Figma", "UI/UX", "Design Thinking"],
      },
    ],
  },
]

// Function to get a recruiter by ID
export function getRecruiterById(id: string) {
  return recruiterUsers.find((recruiter) => recruiter.id === id)
}

// Enhanced student data with more details for recruiters
export const enhancedStudentData = [
  {
    id: "student-1",
    fullName: "Alex Johnson",
    email: "alex.johnson@example.com",
    phone: "+1 (555) 123-4567",
    portfolio: "https://alexjohnson.dev",
    resume: "https://alexjohnson.dev/resume.pdf",
    github: "https://github.com/alexjohnson",
    linkedin: "https://linkedin.com/in/alexjohnson",
    skills: ["React", "TypeScript", "Node.js", "UI/UX Design", "Next.js"],
    university: "Stanford University",
    major: "Computer Science",
    graduationYear: 2024,
    gpa: 3.8,
    profileImage: "/placeholder.svg?height=200&width=200",
    bio: "Computer Science student passionate about web development and UI/UX design. Looking for internship opportunities.",
    projects: [
      {
        title: "E-commerce Platform",
        description: "Built a full-stack e-commerce platform using React, Node.js, and MongoDB",
        link: "https://github.com/alexjohnson/ecommerce",
      },
      {
        title: "AI Chatbot",
        description: "Developed a conversational AI chatbot using natural language processing",
        link: "https://github.com/alexjohnson/chatbot",
      },
    ],
    experience: [
      {
        title: "Frontend Developer Intern",
        company: "TechStart",
        duration: "Summer 2023",
        description: "Developed and maintained features for a React-based web application",
      },
    ],
    availability: "Available for Summer 2024 internships",
    preferredRoles: ["Frontend Developer", "Full Stack Developer", "UI/UX Developer"],
    preferredLocations: ["San Francisco, CA", "Remote"],
    matchScore: 92,
  },
  {
    id: "student-2",
    fullName: "Sophia Chen",
    email: "sophia.chen@example.com",
    phone: "+1 (555) 234-5678",
    portfolio: "https://sophiachen.dev",
    resume: "https://sophiachen.dev/resume.pdf",
    github: "https://github.com/sophiachen",
    linkedin: "https://linkedin.com/in/sophiachen",
    skills: ["Python", "Machine Learning", "Data Science", "SQL", "TensorFlow"],
    university: "MIT",
    major: "Data Science",
    graduationYear: 2023,
    gpa: 3.9,
    profileImage: "/placeholder.svg?height=200&width=200",
    bio: "Data Science student with a focus on machine learning and AI. Seeking opportunities in data analysis and ML engineering.",
    projects: [
      {
        title: "Predictive Analytics Tool",
        description: "Created a tool that predicts customer behavior using machine learning algorithms",
        link: "https://github.com/sophiachen/predictive-analytics",
      },
      {
        title: "Natural Language Processing Library",
        description: "Developed a Python library for text analysis and sentiment detection",
        link: "https://github.com/sophiachen/nlp-library",
      },
    ],
    experience: [
      {
        title: "Data Science Intern",
        company: "DataCorp",
        duration: "Fall 2022",
        description: "Analyzed large datasets and built predictive models for customer insights",
      },
    ],
    availability: "Available immediately for full-time positions",
    preferredRoles: ["Data Scientist", "Machine Learning Engineer", "AI Researcher"],
    preferredLocations: ["Boston, MA", "New York, NY", "Remote"],
    matchScore: 88,
  },
  {
    id: "student-3",
    fullName: "Marcus Williams",
    email: "marcus.williams@example.com",
    phone: "+1 (555) 345-6789",
    portfolio: "https://marcuswilliams.dev",
    resume: "https://marcuswilliams.dev/resume.pdf",
    github: "https://github.com/marcuswilliams",
    linkedin: "https://linkedin.com/in/marcuswilliams",
    skills: ["Java", "Spring Boot", "Android", "Kotlin", "Firebase"],
    university: "UC Berkeley",
    major: "Software Engineering",
    graduationYear: 2025,
    gpa: 3.7,
    profileImage: "/placeholder.svg?height=200&width=200",
    bio: "Software Engineering student specializing in mobile app development. Looking for Android development opportunities.",
    projects: [
      {
        title: "Fitness Tracking App",
        description: "Developed an Android app for tracking workouts and nutrition",
        link: "https://github.com/marcuswilliams/fitness-app",
      },
      {
        title: "Smart Home Controller",
        description: "Built a mobile app to control IoT devices using Firebase and Kotlin",
        link: "https://github.com/marcuswilliams/smart-home",
      },
    ],
    experience: [
      {
        title: "Android Developer Intern",
        company: "MobileInnovations",
        duration: "Spring 2023",
        description: "Developed features for a popular Android application with over 100k downloads",
      },
    ],
    availability: "Available for Summer 2024 internships",
    preferredRoles: ["Android Developer", "Mobile Engineer", "Java Developer"],
    preferredLocations: ["San Francisco, CA", "Seattle, WA"],
    matchScore: 75,
  },
  {
    id: "student-4",
    fullName: "Olivia Martinez",
    email: "olivia.martinez@example.com",
    phone: "+1 (555) 456-7890",
    portfolio: "https://oliviamartinez.dev",
    resume: "https://oliviamartinez.dev/resume.pdf",
    github: "https://github.com/oliviamartinez",
    linkedin: "https://linkedin.com/in/oliviamartinez",
    skills: ["UI/UX Design", "Figma", "Adobe XD", "HTML", "CSS", "JavaScript"],
    university: "Rhode Island School of Design",
    major: "Graphic Design",
    graduationYear: 2024,
    gpa: 3.9,
    profileImage: "/placeholder.svg?height=200&width=200",
    bio: "Design student with a passion for creating beautiful and functional user interfaces. Seeking UI/UX design opportunities.",
    projects: [
      {
        title: "E-learning Platform Redesign",
        description: "Redesigned the user interface for an e-learning platform to improve user experience",
        link: "https://oliviamartinez.dev/projects/elearning",
      },
      {
        title: "Mobile Banking App",
        description: "Created the UI/UX design for a mobile banking application",
        link: "https://oliviamartinez.dev/projects/banking-app",
      },
    ],
    experience: [
      {
        title: "UI/UX Design Intern",
        company: "DesignStudio",
        duration: "Summer 2023",
        description: "Created wireframes, prototypes, and visual designs for web and mobile applications",
      },
    ],
    availability: "Available for part-time work and Summer 2024 internships",
    preferredRoles: ["UI/UX Designer", "Product Designer", "Interaction Designer"],
    preferredLocations: ["New York, NY", "Boston, MA", "Remote"],
    matchScore: 95,
  },
  {
    id: "student-5",
    fullName: "Ethan Kim",
    email: "ethan.kim@example.com",
    phone: "+1 (555) 567-8901",
    portfolio: "https://ethankim.dev",
    resume: "https://ethankim.dev/resume.pdf",
    github: "https://github.com/ethankim",
    linkedin: "https://linkedin.com/in/ethankim",
    skills: ["React Native", "Flutter", "Mobile Development", "JavaScript", "TypeScript"],
    university: "Carnegie Mellon University",
    major: "Human-Computer Interaction",
    graduationYear: 2023,
    gpa: 3.8,
    profileImage: "/placeholder.svg?height=200&width=200",
    bio: "HCI student focused on mobile app development. Looking for opportunities to create intuitive and engaging mobile experiences.",
    projects: [
      {
        title: "Cross-platform Delivery App",
        description: "Built a food delivery app using React Native that works on both iOS and Android",
        link: "https://github.com/ethankim/delivery-app",
      },
      {
        title: "Augmented Reality Shopping Experience",
        description: "Developed an AR shopping app that allows users to visualize products in their home",
        link: "https://github.com/ethankim/ar-shopping",
      },
    ],
    experience: [
      {
        title: "Mobile Developer Intern",
        company: "AppWorks",
        duration: "Fall 2022",
        description: "Developed and maintained features for a React Native application",
      },
    ],
    availability: "Available immediately for full-time positions",
    preferredRoles: ["Mobile Developer", "React Native Developer", "Flutter Developer"],
    preferredLocations: ["San Francisco, CA", "New York, NY", "Seattle, WA", "Remote"],
    matchScore: 82,
  },
  {
    id: "student-6",
    fullName: "Zoe Garcia",
    email: "zoe.garcia@example.com",
    phone: "+1 (555) 678-9012",
    portfolio: "https://zoegarcia.dev",
    resume: "https://zoegarcia.dev/resume.pdf",
    github: "https://github.com/zoegarcia",
    linkedin: "https://linkedin.com/in/zoegarcia",
    skills: ["AWS", "DevOps", "Docker", "Kubernetes", "Terraform", "Python"],
    university: "Georgia Tech",
    major: "Computer Engineering",
    graduationYear: 2023,
    gpa: 3.7,
    profileImage: "/placeholder.svg?height=200&width=200",
    bio: "Computer Engineering student specializing in cloud infrastructure and DevOps. Looking for opportunities in cloud engineering.",
    projects: [
      {
        title: "Automated Deployment Pipeline",
        description: "Created a CI/CD pipeline using GitHub Actions, Docker, and AWS",
        link: "https://github.com/zoegarcia/deployment-pipeline",
      },
      {
        title: "Kubernetes Cluster Manager",
        description: "Developed a tool to simplify Kubernetes cluster management",
        link: "https://github.com/zoegarcia/k8s-manager",
      },
    ],
    experience: [
      {
        title: "DevOps Intern",
        company: "CloudTech",
        duration: "Summer 2022",
        description: "Implemented infrastructure as code using Terraform and managed AWS resources",
      },
    ],
    availability: "Available immediately for full-time positions",
    preferredRoles: ["DevOps Engineer", "Cloud Engineer", "Site Reliability Engineer"],
    preferredLocations: ["Atlanta, GA", "Austin, TX", "Remote"],
    matchScore: 78,
  },
  {
    id: "student-7",
    fullName: "Benjamin Taylor",
    email: "benjamin.taylor@example.com",
    phone: "+1 (555) 789-0123",
    portfolio: "https://benjamintaylor.dev",
    resume: "https://benjamintaylor.dev/resume.pdf",
    github: "https://github.com/benjamintaylor",
    linkedin: "https://linkedin.com/in/benjamintaylor",
    skills: ["C++", "Game Development", "Unity", "Unreal Engine", "3D Modeling"],
    university: "University of Southern California",
    major: "Game Development",
    graduationYear: 2024,
    gpa: 3.6,
    profileImage: "/placeholder.svg?height=200&width=200",
    bio: "Game Development student passionate about creating immersive gaming experiences. Looking for opportunities in game programming.",
    projects: [
      {
        title: "3D Adventure Game",
        description: "Developed a 3D adventure game using Unreal Engine with custom character mechanics",
        link: "https://github.com/benjamintaylor/adventure-game",
      },
      {
        title: "Mobile Puzzle Game",
        description: "Created a puzzle game for iOS and Android using Unity",
        link: "https://github.com/benjamintaylor/puzzle-game",
      },
    ],
    experience: [
      {
        title: "Game Developer Intern",
        company: "GameStudio",
        duration: "Spring 2023",
        description: "Worked on gameplay mechanics and optimization for a PC game",
      },
    ],
    availability: "Available for Summer 2024 internships",
    preferredRoles: ["Game Developer", "C++ Developer", "Unity Developer"],
    preferredLocations: ["Los Angeles, CA", "San Francisco, CA", "Seattle, WA"],
    matchScore: 65,
  },
  {
    id: "student-8",
    fullName: "Aisha Patel",
    email: "aisha.patel@example.com",
    phone: "+1 (555) 890-1234",
    portfolio: "https://aishapatel.dev",
    resume: "https://aishapatel.dev/resume.pdf",
    github: "https://github.com/aishapatel",
    linkedin: "https://linkedin.com/in/aishapatel",
    skills: ["Cybersecurity", "Network Security", "Ethical Hacking", "Python", "Linux"],
    university: "Purdue University",
    major: "Cybersecurity",
    graduationYear: 2023,
    gpa: 3.9,
    profileImage: "/placeholder.svg?height=200&width=200",
    bio: "Cybersecurity student with a focus on network security and ethical hacking. Looking for opportunities in information security.",
    projects: [
      {
        title: "Vulnerability Scanner",
        description: "Developed a tool to scan networks for security vulnerabilities",
        link: "https://github.com/aishapatel/vulnerability-scanner",
      },
      {
        title: "Secure Authentication System",
        description: "Created a multi-factor authentication system with enhanced security features",
        link: "https://github.com/aishapatel/secure-auth",
      },
    ],
    experience: [
      {
        title: "Security Analyst Intern",
        company: "CyberDefense",
        duration: "Fall 2022",
        description: "Conducted security assessments and helped implement security controls",
      },
    ],
    availability: "Available immediately for full-time positions",
    preferredRoles: ["Security Engineer", "Cybersecurity Analyst", "Penetration Tester"],
    preferredLocations: ["Chicago, IL", "Washington, DC", "Remote"],
    matchScore: 85,
  },
  {
    id: "student-9",
    fullName: "Jordan Lee",
    email: "jordan.lee@example.com",
    phone: "+1 (555) 901-2345",
    portfolio: "https://jordanlee.dev",
    resume: "https://jordanlee.dev/resume.pdf",
    github: "https://github.com/jordanlee",
    linkedin: "https://linkedin.com/in/jordanlee",
    skills: ["Product Management", "Agile", "User Research", "Data Analysis", "Prototyping"],
    university: "Harvard University",
    major: "Business Administration",
    minor: "Computer Science",
    graduationYear: 2024,
    gpa: 3.8,
    profileImage: "/placeholder.svg?height=200&width=200",
    bio: "Business student with a technical background, passionate about product management. Looking for opportunities to build innovative products.",
    projects: [
      {
        title: "Healthcare Scheduling Platform",
        description: "Led the development of a platform to streamline healthcare appointments",
        link: "https://jordanlee.dev/projects/healthcare-platform",
      },
      {
        title: "Sustainability Tracking App",
        description: "Managed the creation of an app to help users reduce their carbon footprint",
        link: "https://jordanlee.dev/projects/sustainability-app",
      },
    ],
    experience: [
      {
        title: "Product Management Intern",
        company: "TechInnovate",
        duration: "Summer 2023",
        description: "Conducted user research, created product roadmaps, and coordinated with engineering teams",
      },
    ],
    availability: "Available for Summer 2024 internships",
    preferredRoles: ["Product Manager", "Associate Product Manager", "Product Analyst"],
    preferredLocations: ["Boston, MA", "New York, NY", "San Francisco, CA", "Remote"],
    matchScore: 90,
  },
  {
    id: "student-10",
    fullName: "Ryan Nguyen",
    email: "ryan.nguyen@example.com",
    phone: "+1 (555) 012-3456",
    portfolio: "https://ryannguyen.dev",
    resume: "https://ryannguyen.dev/resume.pdf",
    github: "https://github.com/ryannguyen",
    linkedin: "https://linkedin.com/in/ryannguyen",
    skills: ["Blockchain", "Smart Contracts", "Solidity", "Web3.js", "Ethereum", "JavaScript"],
    university: "University of California, Los Angeles",
    major: "Computer Science",
    graduationYear: 2023,
    gpa: 3.7,
    profileImage: "/placeholder.svg?height=200&width=200",
    bio: "Computer Science student specializing in blockchain technology and decentralized applications. Looking for opportunities in blockchain development.",
    projects: [
      {
        title: "Decentralized Exchange",
        description: "Built a decentralized cryptocurrency exchange using Ethereum smart contracts",
        link: "https://github.com/ryannguyen/dex",
      },
      {
        title: "NFT Marketplace",
        description: "Developed a platform for creating and trading NFTs on the Ethereum blockchain",
        link: "https://github.com/ryannguyen/nft-marketplace",
      },
    ],
    experience: [
      {
        title: "Blockchain Developer Intern",
        company: "BlockTech",
        duration: "Spring 2023",
        description: "Developed and audited smart contracts for decentralized applications",
      },
    ],
    availability: "Available immediately for full-time positions",
    preferredRoles: ["Blockchain Developer", "Smart Contract Engineer", "Web3 Developer"],
    preferredLocations: ["Los Angeles, CA", "San Francisco, CA", "New York, NY", "Remote"],
    matchScore: 72,
  },
]

// Function to get a student by ID
export function getEnhancedStudentById(id: string) {
  return enhancedStudentData.find((student) => student.id === id)
}

// Available skills for filtering and selection
export const availableSkills = [
  "React",
  "TypeScript",
  "JavaScript",
  "Node.js",
  "Next.js",
  "Vue.js",
  "Angular",
  "Python",
  "Django",
  "Flask",
  "Ruby",
  "Ruby on Rails",
  "PHP",
  "Laravel",
  "Java",
  "Spring Boot",
  "C#",
  ".NET",
  "Go",
  "Rust",
  "Swift",
  "Kotlin",
  "Flutter",
  "React Native",
  "AWS",
  "Azure",
  "Google Cloud",
  "Docker",
  "Kubernetes",
  "GraphQL",
  "REST API",
  "SQL",
  "MongoDB",
  "PostgreSQL",
  "MySQL",
  "Redis",
  "UI/UX Design",
  "Figma",
  "Adobe XD",
  "Sketch",
  "HTML",
  "CSS",
  "Sass",
  "Tailwind CSS",
  "Bootstrap",
  "Material UI",
  "DevOps",
  "CI/CD",
  "Git",
  "Testing",
  "Jest",
  "Cypress",
  "Selenium",
  "Machine Learning",
  "Data Science",
  "Blockchain",
  "Smart Contracts",
  "Web3",
  "Solidity",
  "Project Management",
  "Agile",
  "Scrum",
  "Product Management",
  "Cybersecurity",
  "Network Security",
  "Ethical Hacking",
  "Game Development",
  "Unity",
  "Unreal Engine",
  "3D Modeling",
  "Mobile Development",
  "Android",
  "iOS",
  "Firebase",
  "TensorFlow",
  "PyTorch",
  "Natural Language Processing",
  "Computer Vision",
]

// Universities for filtering
export const universities = [
  "Stanford University",
  "MIT",
  "UC Berkeley",
  "Rhode Island School of Design",
  "Carnegie Mellon University",
  "Georgia Tech",
  "University of Southern California",
  "Purdue University",
  "Harvard University",
  "University of California, Los Angeles",
  "California Institute of Technology",
  "University of Michigan",
  "Cornell University",
  "University of Washington",
  "University of Texas at Austin",
]

// Graduation years for filtering
export const graduationYears = [2023, 2024, 2025, 2026, 2027]

// Locations for filtering
export const locations = [
  "San Francisco, CA",
  "New York, NY",
  "Boston, MA",
  "Seattle, WA",
  "Los Angeles, CA",
  "Chicago, IL",
  "Austin, TX",
  "Atlanta, GA",
  "Washington, DC",
  "Remote",
]

// Roles for filtering
export const roles = [
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "Mobile Developer",
  "UI/UX Designer",
  "Data Scientist",
  "Machine Learning Engineer",
  "DevOps Engineer",
  "Cloud Engineer",
  "Security Engineer",
  "Product Manager",
  "Game Developer",
  "Blockchain Developer",
]

